name: Deploy Workflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate Deployment
        run: echo "Deployment completed successfully."

  notify_status:
    needs: deploy
    uses: ./.github/workflows/notify-status.yml
    with:
      deployment_status: ${{ needs.deploy.result }} # "success" or "failure"
      repo: ${{ github.repository }}
      sha: ${{ github.sha }}
      recipient_email: "kturakannavar@deloitte.com"
