name: Simple Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}  # Pass job status (success/failure)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deployment Step
        run: |
          echo "Deploying application..."
          # To simulate failure, uncomment:
          # exit 1

  notify_status:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Notify via Reusable Workflow
        uses: ./.github/workflows/notify-status.yml
        with:
          deployment_status: ${{ needs.deploy.outputs.status }}
          repo: ${{ github.repository }}
          sha: ${{ github.sha }}
          recipient_email: your_email@example.com     # CHANGE to your destination email
