name: Send Email Notification

on:
  workflow_dispatch:
    inputs:
      deployment_status:
        description: 'The deployment status'
        required: true
        default: 'Success'
      recipient_email:
        description: 'Recipient email address'
        required: true
        default: 'recipient@example.com'
      repo:
        description: 'Repository name'
        required: true
        default: ${{ github.repository }}
      sha:
        description: 'Commit SHA'
        required: true
        default: ${{ github.sha }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Deployment Status: ${{ github.event.inputs.deployment_status }}"
          to: ${{ github.event.inputs.recipient_email }}
          from: ${{ secrets.GMAIL_USERNAME }}
          html_body: |
            <p>Automated Deployment Notification</p>
            <ul>
              <li><strong>Status:</strong> ${{ github.event.inputs.deployment_status }}</li>
              <li><strong>Repository:</strong> ${{ github.event.inputs.repo }}</li>
              <li><strong>SHA:</strong> ${{ github.event.inputs.sha }}</li>
            </ul>
