name: Notify Deployment Status

on:
  workflow_call:
    inputs:
      deployment_status:
        required: true
        type: string
      repo:
        required: true
        type: string
      sha:
        required: true
        type: string
      recipient_email:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: mattdavis0351/send-email@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "[${{ inputs.repo }}] Deployment Status: ${{ inputs.deployment_status }}"
          body: |
            Repository: ${{ inputs.repo }}
            Commit: ${{ inputs.sha }}
            Deployment Status: ${{ inputs.deployment_status }}
          to: ${{ inputs.recipient_email }}
          from: ${{ secrets.SMTP_USERNAME }}
