on:
  workflow_call:
    inputs:
      deployment_status:
        required: true
        type: string
      repo:
        required: true
        type: string
      sha:
        required: true
        type: string
      recipient_email:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send deployment notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: "komalgt@gmail.com"
          subject: "Deployment Status: ${{ inputs.deployment_status }}"
          to: ${{ inputs.recipient_email }}
          html_body: |
            <p>Automated Deployment Notification</p>
            <p><strong>Status:</strong> ${{ inputs.deployment_status }}</p>
            <p><strong>Repository:</strong> ${{ inputs.repo }}</p>
            <p><strong>SHA:</strong> ${{ inputs.sha }}</p>
