on:
  workflow_call:
    inputs:
      deployment_status:
        required: true
        type: string
      repo:
        required: true
        type: string
      sha:
        required: true
        type: string
      recipient_email:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Output Deployment Notification
        run: |
          echo "Deployment Status: ${{ inputs.deployment_status }}"
          echo "Repository: ${{ inputs.repo }}"
          echo "Commit SHA: ${{ inputs.sha }}"
          echo "Recipient Email: ${{ inputs.recipient_email }}"
